create table cars (
	id bigserial not null primary key,
	make varchar(50) not null,
	model varchar(50) not null,
	price numeric(19, 2) not null
);
insert into cars (make, model, price) values ('Dodge', 'Magnum', '73449.28');
insert into cars (make, model, price) values ('Volkswagen', 'New Beetle', '49850.42');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '48951.70');
insert into cars (make, model, price) values ('Chevrolet', 'HHR', '93987.53');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '29149.72');
insert into cars (make, model, price) values ('Suzuki', 'X-90', '41155.58');
insert into cars (make, model, price) values ('Maybach', 'Landaulet', '44635.96');
insert into cars (make, model, price) values ('Ford', 'Bronco', '39090.94');
insert into cars (make, model, price) values ('Mazda', 'RX-7', '91761.37');
insert into cars (make, model, price) values ('Mercury', 'Sable', '73660.20');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '84993.35');
insert into cars (make, model, price) values ('Jeep', 'Liberty', '69949.99');
insert into cars (make, model, price) values ('Kia', 'Optima', '80893.98');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '24681.68');
insert into cars (make, model, price) values ('Saab', '9000', '70088.17');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 3500', '89859.44');
insert into cars (make, model, price) values ('Toyota', 'Avalon', '99279.01');
insert into cars (make, model, price) values ('GMC', 'Yukon', '16119.91');
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt', '75863.32');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '28337.80');
insert into cars (make, model, price) values ('Kia', 'Mentor', '32105.39');
insert into cars (make, model, price) values ('Volvo', 'S40', '74333.79');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '52938.55');
insert into cars (make, model, price) values ('Porsche', '968', '35752.93');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '72885.76');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 1500', '80411.15');
insert into cars (make, model, price) values ('Subaru', 'Outback Sport', '36914.93');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '95314.95');
insert into cars (make, model, price) values ('Volkswagen', 'Golf', '80156.36');
insert into cars (make, model, price) values ('Toyota', 'RAV4', '64722.04');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '55920.29');
insert into cars (make, model, price) values ('Ford', 'Ranger', '19917.22');
insert into cars (make, model, price) values ('Ford', 'Festiva', '51011.53');
insert into cars (make, model, price) values ('Mitsubishi', 'GTO', '91287.27');
insert into cars (make, model, price) values ('BMW', '7 Series', '89464.69');
insert into cars (make, model, price) values ('Dodge', 'Journey', '18499.34');
insert into cars (make, model, price) values ('Toyota', 'Camry', '11164.56');
insert into cars (make, model, price) values ('Subaru', 'Justy', '82508.73');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '74305.08');
insert into cars (make, model, price) values ('Ford', 'Explorer', '91961.90');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '19779.54');
insert into cars (make, model, price) values ('Mercury', 'Capri', '61197.21');
insert into cars (make, model, price) values ('Hummer', 'H3', '65341.78');
insert into cars (make, model, price) values ('Oldsmobile', 'Toronado', '76429.89');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '17537.41');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '70963.51');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '85904.29');
insert into cars (make, model, price) values ('Honda', 'Insight', '17476.87');
insert into cars (make, model, price) values ('BMW', 'M6', '75722.22');
insert into cars (make, model, price) values ('Pontiac', 'Vibe', '50668.27');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 2500', '84176.32');
insert into cars (make, model, price) values ('Ford', 'Taurus X', '37405.48');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '97362.40');
insert into cars (make, model, price) values ('Chrysler', 'PT Cruiser', '25979.15');
insert into cars (make, model, price) values ('Toyota', 'Tundra', '69711.67');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '37079.01');
insert into cars (make, model, price) values ('Saturn', 'Ion', '73043.70');
insert into cars (make, model, price) values ('Cadillac', 'Seville', '76330.18');
insert into cars (make, model, price) values ('Suzuki', 'Daewoo Lacetti', '80676.15');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '58934.93');
insert into cars (make, model, price) values ('Volkswagen', 'Golf', '17376.00');
insert into cars (make, model, price) values ('Nissan', 'Armada', '20483.22');
insert into cars (make, model, price) values ('Dodge', 'Durango', '88069.48');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 3500', '10422.93');
insert into cars (make, model, price) values ('GMC', 'Acadia', '52267.69');
insert into cars (make, model, price) values ('Kia', 'Forte', '24444.66');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '80453.31');
insert into cars (make, model, price) values ('Jeep', 'Wrangler', '22027.29');
insert into cars (make, model, price) values ('Volkswagen', 'Golf', '93814.28');
insert into cars (make, model, price) values ('Kia', 'Spectra', '94369.68');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '28692.96');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '92993.72');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '75977.16');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '97022.60');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '49314.76');
insert into cars (make, model, price) values ('Pontiac', 'Firefly', '42375.02');
insert into cars (make, model, price) values ('Toyota', 'Venza', '86147.08');
insert into cars (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '96473.94');
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', '49404.90');
insert into cars (make, model, price) values ('Suzuki', 'Vitara', '64587.86');
insert into cars (make, model, price) values ('BMW', 'M3', '19979.74');
insert into cars (make, model, price) values ('Toyota', 'Matrix', '43158.07');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '97900.53');
insert into cars (make, model, price) values ('Ford', 'F-250 Super Duty', '55641.73');
insert into cars (make, model, price) values ('Chevrolet', 'Venture', '88351.86');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500', '93062.92');
insert into cars (make, model, price) values ('Lexus', 'SC', '20076.93');
insert into cars (make, model, price) values ('BMW', '1 Series', '82359.49');
insert into cars (make, model, price) values ('Ford', 'Mustang', '60591.65');
insert into cars (make, model, price) values ('Chevrolet', 'Aveo', '54517.71');
insert into cars (make, model, price) values ('Ford', 'F350', '33978.87');
insert into cars (make, model, price) values ('Lincoln', 'Continental', '51021.41');
insert into cars (make, model, price) values ('Audi', 'A3', '29302.35');
insert into cars (make, model, price) values ('Eagle', 'Vision', '11326.85');
insert into cars (make, model, price) values ('Nissan', 'Pathfinder', '86153.77');
insert into cars (make, model, price) values ('Aston Martin', 'V8 Vantage S', '93569.51');
insert into cars (make, model, price) values ('Suzuki', 'Samurai', '18853.83');
insert into cars (make, model, price) values ('Infiniti', 'JX', '94652.67');
insert into cars (make, model, price) values ('Infiniti', 'QX', '19510.02');
insert into cars (make, model, price) values ('Mercury', 'Topaz', '44124.75');
insert into cars (make, model, price) values ('Acura', 'RSX', '21079.94');
insert into cars (make, model, price) values ('Chevrolet', 'Impala', '83712.04');
insert into cars (make, model, price) values ('Bentley', 'Continental GT', '55969.92');
insert into cars (make, model, price) values ('Lamborghini', 'Countach', '34519.72');
insert into cars (make, model, price) values ('GMC', 'Sonoma', '77756.58');
insert into cars (make, model, price) values ('Pontiac', 'Sunfire', '11360.55');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '30601.79');
insert into cars (make, model, price) values ('GMC', 'Savana 2500', '21534.46');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '28837.40');
insert into cars (make, model, price) values ('Kia', 'Sportage', '23736.35');
insert into cars (make, model, price) values ('Buick', 'Century', '86553.73');
insert into cars (make, model, price) values ('Mazda', 'Mazda6', '81364.49');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '35521.72');
insert into cars (make, model, price) values ('Ford', 'Mustang', '88665.68');
insert into cars (make, model, price) values ('Chrysler', '300', '47004.61');
insert into cars (make, model, price) values ('Acura', 'RSX', '67043.96');
insert into cars (make, model, price) values ('Ford', 'Taurus', '62502.39');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '98128.70');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '79480.66');
insert into cars (make, model, price) values ('Cadillac', 'SRX', '65523.26');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '78734.55');
insert into cars (make, model, price) values ('Saturn', 'Ion', '66394.34');
insert into cars (make, model, price) values ('BMW', '530', '24753.00');
insert into cars (make, model, price) values ('Audi', 'S4', '84151.17');
insert into cars (make, model, price) values ('Jeep', 'Wrangler', '27525.58');
insert into cars (make, model, price) values ('Mazda', 'Protege', '60702.53');
insert into cars (make, model, price) values ('Mercury', 'Montego', '77597.72');
insert into cars (make, model, price) values ('Dodge', 'Durango', '42302.26');
insert into cars (make, model, price) values ('Ford', 'E-Series', '34652.50');
insert into cars (make, model, price) values ('Plymouth', 'Breeze', '49988.01');
insert into cars (make, model, price) values ('Lotus', 'Elise', '27890.97');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '11857.34');
insert into cars (make, model, price) values ('Maserati', 'Spyder', '31302.16');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '88625.89');
insert into cars (make, model, price) values ('Mitsubishi', 'Diamante', '16596.06');
insert into cars (make, model, price) values ('Audi', '80', '55927.80');
insert into cars (make, model, price) values ('Rambler', 'Classic', '17870.42');
insert into cars (make, model, price) values ('Mercedes-Benz', 'M-Class', '95470.55');
insert into cars (make, model, price) values ('GMC', 'Yukon', '75118.22');
insert into cars (make, model, price) values ('Bentley', 'Azure', '41637.31');
insert into cars (make, model, price) values ('Buick', 'Roadmaster', '25738.24');
insert into cars (make, model, price) values ('Acura', 'TL', '94465.50');
insert into cars (make, model, price) values ('Hyundai', 'Azera', '15514.10');
insert into cars (make, model, price) values ('GMC', 'Rally Wagon G3500', '43611.69');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '76609.71');
insert into cars (make, model, price) values ('BMW', 'M6', '89002.16');
insert into cars (make, model, price) values ('Lamborghini', 'Gallardo', '94061.94');
insert into cars (make, model, price) values ('GMC', 'Yukon', '91479.08');
insert into cars (make, model, price) values ('Chrysler', 'LeBaron', '14896.46');
insert into cars (make, model, price) values ('Mazda', 'Tribute', '46152.98');
insert into cars (make, model, price) values ('Toyota', 'RAV4', '63574.04');
insert into cars (make, model, price) values ('Volkswagen', 'New Beetle', '96395.15');
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', '44620.78');
insert into cars (make, model, price) values ('GMC', 'Yukon', '59232.28');
insert into cars (make, model, price) values ('Mazda', 'MPV', '36675.92');
insert into cars (make, model, price) values ('GMC', 'Jimmy', '97500.15');
insert into cars (make, model, price) values ('Ford', 'Explorer Sport Trac', '51461.32');
insert into cars (make, model, price) values ('Audi', 'S6', '24969.30');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '10827.02');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '65414.82');
insert into cars (make, model, price) values ('Mercedes-Benz', '300TE', '62904.38');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500 Club', '79921.29');
insert into cars (make, model, price) values ('Jeep', 'Wrangler', '82960.75');
insert into cars (make, model, price) values ('Pontiac', 'Aztek', '26207.20');
insert into cars (make, model, price) values ('Mercury', 'Villager', '50270.26');
insert into cars (make, model, price) values ('Lincoln', 'Continental Mark VII', '95424.14');
insert into cars (make, model, price) values ('Honda', 'Insight', '70790.50');
insert into cars (make, model, price) values ('Nissan', 'NV3500', '72733.99');
insert into cars (make, model, price) values ('Audi', '5000S', '67524.15');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '54944.53');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '24951.94');
insert into cars (make, model, price) values ('Saab', '900', '46135.12');
insert into cars (make, model, price) values ('Lexus', 'ES', '93172.90');
insert into cars (make, model, price) values ('BMW', 'X5', '36957.32');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '71070.33');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '82610.91');
insert into cars (make, model, price) values ('Ferrari', 'F430', '43555.32');
insert into cars (make, model, price) values ('Rolls-Royce', 'Phantom', '63311.81');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '19153.10');
insert into cars (make, model, price) values ('Buick', 'Somerset', '64808.55');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '81203.23');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '71949.99');
insert into cars (make, model, price) values ('Mazda', 'Tribute', '95394.15');
insert into cars (make, model, price) values ('Lexus', 'ES', '37609.25');
insert into cars (make, model, price) values ('Mitsubishi', 'Diamante', '12518.51');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '32640.87');
insert into cars (make, model, price) values ('GMC', 'Sierra Hybrid', '76107.01');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '79628.95');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '87955.93');
insert into cars (make, model, price) values ('Volvo', 'S60', '12516.34');
insert into cars (make, model, price) values ('Audi', 'TT', '73646.49');
insert into cars (make, model, price) values ('Kia', 'Carens', '67647.11');
insert into cars (make, model, price) values ('Porsche', 'Boxster', '23922.24');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '10578.19');
insert into cars (make, model, price) values ('Lexus', 'GS', '95577.22');
insert into cars (make, model, price) values ('Lexus', 'LX', '81867.20');
insert into cars (make, model, price) values ('Mazda', 'RX-7', '58985.21');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '33095.51');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '58946.55');
insert into cars (make, model, price) values ('Ford', 'Excursion', '43387.02');
insert into cars (make, model, price) values ('GMC', 'Suburban 2500', '53925.64');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '43729.41');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '53827.43');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '47119.37');
insert into cars (make, model, price) values ('Cadillac', 'XLR', '71352.34');
insert into cars (make, model, price) values ('Kia', 'Spectra', '76329.97');
insert into cars (make, model, price) values ('Audi', 'S6', '94994.25');
insert into cars (make, model, price) values ('Mazda', 'B2600', '21223.49');
insert into cars (make, model, price) values ('Ford', 'Econoline E350', '68519.35');
insert into cars (make, model, price) values ('Audi', 'A4', '11635.58');
insert into cars (make, model, price) values ('Porsche', '911', '56063.65');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '81785.43');
insert into cars (make, model, price) values ('Acura', 'TSX', '45179.69');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '45324.96');
insert into cars (make, model, price) values ('Saab', '900', '59556.69');
insert into cars (make, model, price) values ('GMC', 'Sonoma Club Coupe', '31440.79');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '56028.16');
insert into cars (make, model, price) values ('GMC', 'Vandura 2500', '41739.82');
insert into cars (make, model, price) values ('Ford', 'E250', '40797.23');
insert into cars (make, model, price) values ('Kia', 'Mentor', '95591.67');
insert into cars (make, model, price) values ('Aston Martin', 'DB9', '28540.13');
insert into cars (make, model, price) values ('Honda', 'Accord', '62586.94');
insert into cars (make, model, price) values ('Buick', 'Skylark', '25888.43');
insert into cars (make, model, price) values ('Mazda', 'Familia', '15411.56');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '92993.14');
insert into cars (make, model, price) values ('Mitsubishi', 'Raider', '29481.55');
insert into cars (make, model, price) values ('Jaguar', 'XJ Series', '23534.20');
insert into cars (make, model, price) values ('Porsche', 'Boxster', '60222.06');
insert into cars (make, model, price) values ('Nissan', 'Titan', '37431.51');
insert into cars (make, model, price) values ('Chrysler', '300', '77713.25');
insert into cars (make, model, price) values ('Lexus', 'LS', '71984.22');
insert into cars (make, model, price) values ('Audi', 'Allroad', '37973.85');
insert into cars (make, model, price) values ('Suzuki', 'Esteem', '54482.47');
insert into cars (make, model, price) values ('Suzuki', 'Kizashi', '33148.70');
insert into cars (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '11919.51');
insert into cars (make, model, price) values ('Honda', 'S2000', '73003.18');
insert into cars (make, model, price) values ('Pontiac', 'G6', '21562.28');
insert into cars (make, model, price) values ('GMC', 'Sonoma', '76819.87');
insert into cars (make, model, price) values ('Suzuki', 'Daewoo Lacetti', '38578.86');
insert into cars (make, model, price) values ('Eagle', 'Talon', '38297.75');
insert into cars (make, model, price) values ('Audi', '100', '25126.49');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '80896.00');
insert into cars (make, model, price) values ('Audi', 'A6', '13422.91');
insert into cars (make, model, price) values ('Mitsubishi', 'Truck', '84915.00');
insert into cars (make, model, price) values ('Ford', 'E-Series', '68339.27');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '67760.57');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '82076.60');
insert into cars (make, model, price) values ('Ford', 'Mustang', '48644.13');
insert into cars (make, model, price) values ('Land Rover', 'Discovery', '11119.97');
insert into cars (make, model, price) values ('Suzuki', 'Aerio', '47695.25');
insert into cars (make, model, price) values ('Daewoo', 'Leganza', '77987.01');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '86703.63');
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', '97435.80');
insert into cars (make, model, price) values ('Lincoln', 'Continental Mark VII', '12904.82');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '13039.83');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '74760.46');
insert into cars (make, model, price) values ('Jeep', 'Commander', '68936.06');
insert into cars (make, model, price) values ('Jaguar', 'S-Type', '37974.02');
insert into cars (make, model, price) values ('Audi', '200', '26307.68');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '32235.88');
insert into cars (make, model, price) values ('Toyota', 'RAV4', '21188.35');
insert into cars (make, model, price) values ('Lincoln', 'MKS', '23638.14');
insert into cars (make, model, price) values ('Chevrolet', 'G-Series 2500', '32662.44');
insert into cars (make, model, price) values ('Subaru', 'Outback', '96882.11');
insert into cars (make, model, price) values ('Honda', 'Pilot', '91954.95');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '73434.52');
insert into cars (make, model, price) values ('Mercury', 'Tracer', '40457.21');
insert into cars (make, model, price) values ('Maserati', 'Quattroporte', '76159.17');
insert into cars (make, model, price) values ('Ferrari', 'F430', '13881.92');
insert into cars (make, model, price) values ('Suzuki', 'Sidekick', '83120.13');
insert into cars (make, model, price) values ('Mazda', '929', '52290.47');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '10766.28');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 3500', '91091.89');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '55587.49');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '45699.69');
insert into cars (make, model, price) values ('Plymouth', 'Voyager', '46881.17');
insert into cars (make, model, price) values ('Buick', 'Skylark', '58928.25');
insert into cars (make, model, price) values ('Ford', 'Expedition', '99023.20');
insert into cars (make, model, price) values ('Volvo', 'S80', '42241.96');
insert into cars (make, model, price) values ('Infiniti', 'G', '77673.24');
insert into cars (make, model, price) values ('Suzuki', 'Cultus', '37185.71');
insert into cars (make, model, price) values ('Maserati', 'Quattroporte', '18928.32');
insert into cars (make, model, price) values ('Subaru', 'SVX', '40507.94');
insert into cars (make, model, price) values ('BMW', 'M3', '42764.08');
insert into cars (make, model, price) values ('Hyundai', 'Accent', '35460.52');
insert into cars (make, model, price) values ('GMC', '1500 Club Coupe', '92001.55');
insert into cars (make, model, price) values ('Suzuki', 'Grand Vitara', '83409.56');
insert into cars (make, model, price) values ('Studebaker', 'Avanti', '36102.44');
insert into cars (make, model, price) values ('Hyundai', 'Santa Fe', '23600.50');
insert into cars (make, model, price) values ('Toyota', 'MR2', '70574.73');
insert into cars (make, model, price) values ('Toyota', 'T100', '68772.80');
insert into cars (make, model, price) values ('Volvo', 'XC90', '86167.04');
insert into cars (make, model, price) values ('Dodge', 'Charger', '56124.46');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '61065.35');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '16683.23');
insert into cars (make, model, price) values ('Ford', 'E250', '82701.10');
insert into cars (make, model, price) values ('Mercedes-Benz', '400E', '37538.86');
insert into cars (make, model, price) values ('Bentley', 'Azure', '67750.17');
insert into cars (make, model, price) values ('Suzuki', 'Sidekick', '15270.59');
insert into cars (make, model, price) values ('Toyota', 'Camry', '83599.24');
insert into cars (make, model, price) values ('Honda', 'Civic', '54869.16');
insert into cars (make, model, price) values ('Mazda', 'Mazda5', '82432.62');
insert into cars (make, model, price) values ('Buick', 'LaCrosse', '36590.28');
insert into cars (make, model, price) values ('Toyota', 'Camry', '63442.64');
insert into cars (make, model, price) values ('Lexus', 'LS', '16240.97');
insert into cars (make, model, price) values ('Ford', 'Probe', '58817.91');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '20127.73');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '41455.48');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '74674.33');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '67928.95');
insert into cars (make, model, price) values ('Dodge', 'Ram Van B250', '41818.08');
insert into cars (make, model, price) values ('Acura', 'Integra', '51196.97');
insert into cars (make, model, price) values ('Dodge', 'Caravan', '95259.29');
insert into cars (make, model, price) values ('Chevrolet', 'Avalanche', '62029.57');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '52744.24');
insert into cars (make, model, price) values ('Lotus', 'Exige', '11775.79');
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt SS', '70646.45');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '60197.79');
insert into cars (make, model, price) values ('Oldsmobile', 'Cutlass', '17269.87');
insert into cars (make, model, price) values ('Plymouth', 'Fury', '56583.82');
insert into cars (make, model, price) values ('Volkswagen', 'R32', '66240.78');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '16386.12');
insert into cars (make, model, price) values ('Subaru', 'XT', '74184.30');
insert into cars (make, model, price) values ('Infiniti', 'J', '16018.09');
insert into cars (make, model, price) values ('Buick', 'Century', '71802.19');
insert into cars (make, model, price) values ('Acura', 'RL', '33651.60');
insert into cars (make, model, price) values ('Ford', 'EXP', '11135.36');
insert into cars (make, model, price) values ('GMC', 'Rally Wagon 3500', '89771.84');
insert into cars (make, model, price) values ('Ford', 'Escort', '58694.59');
insert into cars (make, model, price) values ('Nissan', 'Pathfinder', '94708.87');
insert into cars (make, model, price) values ('Ford', 'F350', '90730.32');
insert into cars (make, model, price) values ('Pontiac', 'Monterey', '38170.10');
insert into cars (make, model, price) values ('Ford', 'Edge', '44242.38');
insert into cars (make, model, price) values ('Buick', 'Century', '44919.88');
insert into cars (make, model, price) values ('Subaru', 'Forester', '68824.86');
insert into cars (make, model, price) values ('Toyota', 'Prius', '21163.53');
insert into cars (make, model, price) values ('Cadillac', 'Escalade EXT', '19447.02');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '46459.27');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '14159.67');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '99139.91');
insert into cars (make, model, price) values ('Buick', 'Century', '59050.60');
insert into cars (make, model, price) values ('Hyundai', 'Scoupe', '59566.43');
insert into cars (make, model, price) values ('Lexus', 'ES', '24963.09');
insert into cars (make, model, price) values ('GMC', 'Canyon', '55725.46');
insert into cars (make, model, price) values ('Chevrolet', 'Blazer', '12055.68');
insert into cars (make, model, price) values ('Oldsmobile', 'Bravada', '30493.16');
insert into cars (make, model, price) values ('Subaru', 'Outback', '29272.99');
insert into cars (make, model, price) values ('Jaguar', 'XF', '10014.76');
insert into cars (make, model, price) values ('Subaru', 'Justy', '76082.83');
insert into cars (make, model, price) values ('Volkswagen', 'Type 2', '86590.12');
insert into cars (make, model, price) values ('Ford', 'F150', '22137.29');
insert into cars (make, model, price) values ('Plymouth', 'Colt Vista', '14691.09');
insert into cars (make, model, price) values ('Land Rover', 'LR4', '66973.74');
insert into cars (make, model, price) values ('Kia', 'Sedona', '95244.96');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '29726.69');
insert into cars (make, model, price) values ('Suzuki', 'Grand Vitara', '60873.16');
insert into cars (make, model, price) values ('Chevrolet', 'Aveo', '67942.26');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500 Club', '79604.55');
insert into cars (make, model, price) values ('Lexus', 'GS', '51845.96');
insert into cars (make, model, price) values ('Buick', 'Electra', '78072.86');
insert into cars (make, model, price) values ('GMC', '2500 Club Coupe', '96875.12');
insert into cars (make, model, price) values ('Audi', 'A4', '99402.66');
insert into cars (make, model, price) values ('Volvo', 'S60', '23155.37');
insert into cars (make, model, price) values ('GMC', 'Sierra 2500', '48024.56');
insert into cars (make, model, price) values ('BMW', '5 Series', '64636.78');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '61633.17');
insert into cars (make, model, price) values ('Daewoo', 'Lanos', '69143.29');
insert into cars (make, model, price) values ('BMW', '3 Series', '40561.14');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '11896.07');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '81877.09');
insert into cars (make, model, price) values ('Mazda', 'Millenia', '91163.01');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '58249.41');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '35439.32');
insert into cars (make, model, price) values ('Smart', 'Fortwo', '75168.48');
insert into cars (make, model, price) values ('Buick', 'Rainier', '49691.21');
insert into cars (make, model, price) values ('Lexus', 'LX', '21224.41');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '21472.29');
insert into cars (make, model, price) values ('Ford', 'Five Hundred', '17461.90');
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', '38374.81');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '41814.59');
insert into cars (make, model, price) values ('Mercedes-Benz', 'C-Class', '39963.33');
insert into cars (make, model, price) values ('Ford', 'Explorer Sport Trac', '84480.69');
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', '78926.76');
insert into cars (make, model, price) values ('Geo', 'Storm', '67612.32');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '64120.78');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '66223.76');
insert into cars (make, model, price) values ('Cadillac', 'XLR', '16434.63');
insert into cars (make, model, price) values ('Toyota', 'Sienna', '40955.82');
insert into cars (make, model, price) values ('Pontiac', 'Montana', '27684.85');
insert into cars (make, model, price) values ('Jaguar', 'X-Type', '51305.82');
insert into cars (make, model, price) values ('Toyota', '4Runner', '75660.16');
insert into cars (make, model, price) values ('Mazda', 'Tribute', '99458.27');
insert into cars (make, model, price) values ('Lexus', 'IS-F', '64295.12');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '57930.73');
insert into cars (make, model, price) values ('BMW', 'Z8', '70140.46');
insert into cars (make, model, price) values ('Chevrolet', 'G-Series 3500', '43648.41');
insert into cars (make, model, price) values ('Nissan', 'Armada', '84738.39');
insert into cars (make, model, price) values ('Suzuki', 'Esteem', '39973.60');
insert into cars (make, model, price) values ('BMW', 'X5 M', '43503.19');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '24617.87');
insert into cars (make, model, price) values ('Scion', 'tC', '24308.51');
insert into cars (make, model, price) values ('GMC', 'Envoy XL', '17676.20');
insert into cars (make, model, price) values ('Mitsubishi', 'Starion', '78938.64');
insert into cars (make, model, price) values ('Toyota', '4Runner', '41683.49');
insert into cars (make, model, price) values ('Bentley', 'Continental Super', '41697.01');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '35116.02');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '96597.89');
insert into cars (make, model, price) values ('Subaru', 'Baja', '64268.14');
insert into cars (make, model, price) values ('Mitsubishi', '3000GT', '85803.93');
insert into cars (make, model, price) values ('Ford', 'Windstar', '71752.40');
insert into cars (make, model, price) values ('Ford', 'Econoline E150', '11506.91');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '55515.56');
insert into cars (make, model, price) values ('Volvo', 'S60', '77138.08');
insert into cars (make, model, price) values ('Saab', '9000', '96828.30');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '34952.03');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '17458.38');
insert into cars (make, model, price) values ('Honda', 'Element', '35357.93');
insert into cars (make, model, price) values ('Chrysler', 'Prowler', '42875.48');
insert into cars (make, model, price) values ('Volkswagen', 'Passat', '33095.46');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '41116.55');
insert into cars (make, model, price) values ('Saturn', 'Relay', '88229.56');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '57022.79');
insert into cars (make, model, price) values ('Honda', 'Fit', '17225.29');
insert into cars (make, model, price) values ('Toyota', 'Matrix', '96208.73');
insert into cars (make, model, price) values ('Lincoln', 'MKZ', '30502.47');
insert into cars (make, model, price) values ('Honda', 'Passport', '41698.88');
insert into cars (make, model, price) values ('Chevrolet', 'Prizm', '38636.75');
insert into cars (make, model, price) values ('Geo', 'Prizm', '94767.29');
insert into cars (make, model, price) values ('Ford', 'LTD Crown Victoria', '30290.91');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '26190.60');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '81023.99');
insert into cars (make, model, price) values ('Jaguar', 'S-Type', '62219.66');
insert into cars (make, model, price) values ('Volkswagen', 'Tiguan', '22987.03');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '87103.31');
insert into cars (make, model, price) values ('Volvo', 'S80', '35900.10');
insert into cars (make, model, price) values ('MINI', 'Cooper', '71299.62');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg', '99634.99');
insert into cars (make, model, price) values ('Mercury', 'Monterey', '83192.29');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '93421.54');
insert into cars (make, model, price) values ('Ford', 'F-Series', '59335.55');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '59852.00');
insert into cars (make, model, price) values ('Honda', 'CR-V', '99163.60');
insert into cars (make, model, price) values ('BMW', 'X5', '64677.87');
insert into cars (make, model, price) values ('Porsche', '944', '72511.67');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '71930.47');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '57743.65');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '47724.35');
insert into cars (make, model, price) values ('Mercedes-Benz', 'GLK-Class', '16008.53');
insert into cars (make, model, price) values ('BMW', '5 Series', '33063.07');
insert into cars (make, model, price) values ('Lincoln', 'Continental', '24016.53');
insert into cars (make, model, price) values ('Buick', 'Century', '15789.88');
insert into cars (make, model, price) values ('Chevrolet', '3500', '99599.78');
insert into cars (make, model, price) values ('Cadillac', 'Escalade EXT', '85548.24');
insert into cars (make, model, price) values ('Isuzu', 'Axiom', '56394.47');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '79133.02');
insert into cars (make, model, price) values ('Audi', 'Q5', '14207.49');
insert into cars (make, model, price) values ('BMW', '6 Series', '22749.81');
insert into cars (make, model, price) values ('Ford', 'Mustang', '94493.46');
insert into cars (make, model, price) values ('BMW', '525', '95857.15');
insert into cars (make, model, price) values ('Ford', 'Aspire', '12004.22');
insert into cars (make, model, price) values ('Ford', 'Escort', '44996.66');
insert into cars (make, model, price) values ('Ford', 'Flex', '94592.84');
insert into cars (make, model, price) values ('Cadillac', 'Escalade', '80167.99');
insert into cars (make, model, price) values ('Ford', 'Mustang', '49866.40');
insert into cars (make, model, price) values ('Hummer', 'H3T', '51144.66');
insert into cars (make, model, price) values ('Ford', 'Explorer', '27134.86');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '72025.99');
insert into cars (make, model, price) values ('GMC', 'Vandura 3500', '60444.37');
insert into cars (make, model, price) values ('Chevrolet', 'G-Series 1500', '28571.19');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '50094.82');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '77306.71');
insert into cars (make, model, price) values ('Mercedes-Benz', 'W201', '64155.48');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '60519.92');
insert into cars (make, model, price) values ('GMC', '2500', '52842.33');
insert into cars (make, model, price) values ('Mazda', 'RX-7', '74147.70');
insert into cars (make, model, price) values ('Mercedes-Benz', 'M-Class', '13758.33');
insert into cars (make, model, price) values ('Geo', 'Tracker', '36500.82');
insert into cars (make, model, price) values ('Lincoln', 'Continental', '59767.04');
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt', '39759.08');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '10928.52');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '31942.29');
insert into cars (make, model, price) values ('Infiniti', 'M', '63158.47');
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', '59554.49');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '45758.69');
insert into cars (make, model, price) values ('Geo', 'Tracker', '94388.33');
insert into cars (make, model, price) values ('Suzuki', 'Daewoo Lacetti', '96417.52');
insert into cars (make, model, price) values ('Ford', 'E-Series', '22343.82');
insert into cars (make, model, price) values ('Volvo', 'C70', '37135.56');
insert into cars (make, model, price) values ('Porsche', '911', '60121.52');
insert into cars (make, model, price) values ('Volvo', 'XC90', '34530.89');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '65124.25');
insert into cars (make, model, price) values ('Saturn', 'VUE', '45233.04');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '52041.46');
insert into cars (make, model, price) values ('GMC', 'Sonoma', '33281.03');
insert into cars (make, model, price) values ('Acura', 'TL', '29706.12');
insert into cars (make, model, price) values ('Nissan', 'Pathfinder', '59563.59');
insert into cars (make, model, price) values ('Infiniti', 'QX', '71956.57');
insert into cars (make, model, price) values ('Dodge', 'Durango', '71839.72');
insert into cars (make, model, price) values ('Hyundai', 'XG350', '72341.90');
insert into cars (make, model, price) values ('Buick', 'LeSabre', '89830.08');
insert into cars (make, model, price) values ('Honda', 'Civic', '62238.39');
insert into cars (make, model, price) values ('Chevrolet', 'S10', '98634.78');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '32773.82');
insert into cars (make, model, price) values ('GMC', 'Safari', '14576.35');
insert into cars (make, model, price) values ('GMC', '2500 Club Coupe', '15316.49');
insert into cars (make, model, price) values ('Land Rover', 'Discovery', '47238.02');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '79726.69');
insert into cars (make, model, price) values ('Mitsubishi', '3000GT', '86950.21');
insert into cars (make, model, price) values ('Lincoln', 'MKT', '13365.54');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '97109.33');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', '11999.83');
insert into cars (make, model, price) values ('Volkswagen', 'Eos', '47538.65');
insert into cars (make, model, price) values ('Audi', 'A8', '28651.95');
insert into cars (make, model, price) values ('Honda', 'Civic', '69518.46');
insert into cars (make, model, price) values ('Maybach', '57', '22894.67');
insert into cars (make, model, price) values ('Scion', 'tC', '52766.46');
insert into cars (make, model, price) values ('Saab', '900', '38613.21');
insert into cars (make, model, price) values ('Buick', 'Electra', '76331.06');
insert into cars (make, model, price) values ('Bentley', 'Continental Flying Spur', '86180.18');
insert into cars (make, model, price) values ('Lincoln', 'MKX', '10195.93');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '94818.19');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 1500', '86928.16');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', '66703.79');
insert into cars (make, model, price) values ('BMW', 'M3', '19969.56');
insert into cars (make, model, price) values ('Volkswagen', 'Rabbit', '97903.37');
insert into cars (make, model, price) values ('Land Rover', 'Discovery', '83310.86');
insert into cars (make, model, price) values ('Ram', '2500', '72573.58');
insert into cars (make, model, price) values ('Infiniti', 'G37', '64034.22');
insert into cars (make, model, price) values ('Saab', '9-7X', '61121.16');
insert into cars (make, model, price) values ('Citroën', '2CV', '40867.16');
insert into cars (make, model, price) values ('Ford', 'Club Wagon', '58060.75');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '14166.61');
insert into cars (make, model, price) values ('Cadillac', 'DeVille', '57754.53');
insert into cars (make, model, price) values ('Oldsmobile', '88', '24159.18');
insert into cars (make, model, price) values ('Acura', 'TL', '53988.02');
insert into cars (make, model, price) values ('Ford', 'E-Series', '93584.66');
insert into cars (make, model, price) values ('BMW', 'X5', '68857.71');
insert into cars (make, model, price) values ('BMW', '645', '20113.21');
insert into cars (make, model, price) values ('Infiniti', 'G', '88941.02');
insert into cars (make, model, price) values ('Ford', 'F250', '84150.15');
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', '48641.54');
insert into cars (make, model, price) values ('Lincoln', 'Aviator', '36870.01');
insert into cars (make, model, price) values ('Ford', 'Taurus', '67193.45');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 1500', '39282.68');
insert into cars (make, model, price) values ('Chrysler', 'Cirrus', '41101.96');
insert into cars (make, model, price) values ('Audi', 'A8', '52969.46');
insert into cars (make, model, price) values ('Chevrolet', 'S10', '36439.09');
insert into cars (make, model, price) values ('Volkswagen', 'Rabbit', '26390.88');
insert into cars (make, model, price) values ('Oldsmobile', 'Cutlass', '44420.68');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '45402.75');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '57081.84');
insert into cars (make, model, price) values ('Volvo', '960', '42913.80');
insert into cars (make, model, price) values ('Audi', 'S4', '56898.15');
insert into cars (make, model, price) values ('Chevrolet', 'Uplander', '81614.10');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '88428.17');
insert into cars (make, model, price) values ('Jensen', 'Interceptor', '64743.56');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', '30054.39');
insert into cars (make, model, price) values ('Mitsubishi', 'Chariot', '88431.69');
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', '83722.97');
insert into cars (make, model, price) values ('Honda', 'Accord', '93409.09');
insert into cars (make, model, price) values ('Nissan', 'Altima', '86000.78');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '34444.00');
insert into cars (make, model, price) values ('Mitsubishi', 'Precis', '79336.63');
insert into cars (make, model, price) values ('Buick', 'Regal', '48699.71');
insert into cars (make, model, price) values ('Lexus', 'LS', '84488.08');
insert into cars (make, model, price) values ('BMW', '8 Series', '56880.49');
insert into cars (make, model, price) values ('Infiniti', 'EX', '81985.34');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '24065.09');
insert into cars (make, model, price) values ('Dodge', 'Caravan', '60709.21');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '36255.67');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '78906.16');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '38264.63');
insert into cars (make, model, price) values ('Ford', 'Ranger', '72576.41');
insert into cars (make, model, price) values ('Lincoln', 'Mark VIII', '50507.76');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '57866.60');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '64303.21');
insert into cars (make, model, price) values ('Mitsubishi', 'Tredia', '76331.38');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '71360.34');
insert into cars (make, model, price) values ('Toyota', 'Truck Xtracab SR5', '32279.92');
insert into cars (make, model, price) values ('GMC', 'Suburban 1500', '74408.29');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '17923.27');
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', '84024.04');
insert into cars (make, model, price) values ('Cadillac', 'XLR', '87579.99');
insert into cars (make, model, price) values ('BMW', '530', '46023.48');
insert into cars (make, model, price) values ('Chrysler', '300M', '75690.27');
insert into cars (make, model, price) values ('Pontiac', 'Parisienne', '94634.99');
insert into cars (make, model, price) values ('Audi', 'A3', '77070.38');
insert into cars (make, model, price) values ('Porsche', '911', '13031.00');
insert into cars (make, model, price) values ('Chrysler', 'Concorde', '12739.84');
insert into cars (make, model, price) values ('Mitsubishi', 'Mighty Max', '68233.09');
insert into cars (make, model, price) values ('Chrysler', 'LHS', '56436.52');
insert into cars (make, model, price) values ('BMW', 'M3', '22812.49');
insert into cars (make, model, price) values ('Aston Martin', 'V8 Vantage S', '83166.27');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '10864.92');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '17546.13');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '66395.96');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '58670.19');
insert into cars (make, model, price) values ('Mitsubishi', 'Lancer', '99257.29');
insert into cars (make, model, price) values ('Bentley', 'Continental GT', '72441.23');
insert into cars (make, model, price) values ('GMC', 'Safari', '86440.94');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '92228.39');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '28619.07');
insert into cars (make, model, price) values ('Dodge', 'Viper RT/10', '16086.04');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '73611.48');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '25689.53');
insert into cars (make, model, price) values ('BMW', '7 Series', '26579.46');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '11445.88');
insert into cars (make, model, price) values ('Toyota', 'RAV4', '30054.22');
insert into cars (make, model, price) values ('Buick', 'Regal', '89689.31');
insert into cars (make, model, price) values ('GMC', 'Savana', '72706.28');
insert into cars (make, model, price) values ('Plymouth', 'Acclaim', '49005.10');
insert into cars (make, model, price) values ('Pontiac', 'Aztek', '10943.74');
insert into cars (make, model, price) values ('Porsche', '944', '60566.07');
insert into cars (make, model, price) values ('Subaru', 'Justy', '57317.32');
insert into cars (make, model, price) values ('Ford', 'Econoline E150', '70253.84');
insert into cars (make, model, price) values ('Pontiac', 'Montana', '56520.57');
insert into cars (make, model, price) values ('Volvo', 'S70', '44226.79');
insert into cars (make, model, price) values ('Ford', 'GT500', '92360.22');
insert into cars (make, model, price) values ('Infiniti', 'QX56', '65824.43');
insert into cars (make, model, price) values ('Jeep', 'Liberty', '52073.44');
insert into cars (make, model, price) values ('Land Rover', 'LR2', '75626.97');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '10865.08');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '71899.25');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '13688.82');
insert into cars (make, model, price) values ('Land Rover', 'Discovery', '24671.22');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '64695.61');
insert into cars (make, model, price) values ('Dodge', 'Spirit', '77315.04');
insert into cars (make, model, price) values ('Ford', 'Econoline E250', '95488.92');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '69522.06');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '23733.03');
insert into cars (make, model, price) values ('Toyota', 'Sienna', '18533.12');
insert into cars (make, model, price) values ('Jaguar', 'XJ Series', '21367.05');
insert into cars (make, model, price) values ('Rolls-Royce', 'Ghost', '14900.59');
insert into cars (make, model, price) values ('Toyota', 'Sequoia', '36390.57');
insert into cars (make, model, price) values ('Mazda', 'MPV', '94855.92');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '56349.97');
insert into cars (make, model, price) values ('Audi', 'A6', '49572.77');
insert into cars (make, model, price) values ('Honda', 'Civic', '48565.18');
insert into cars (make, model, price) values ('GMC', 'Savana 2500', '21322.00');
insert into cars (make, model, price) values ('Ford', 'Escort', '86807.33');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '68469.26');
insert into cars (make, model, price) values ('Lincoln', 'MKS', '41650.95');
insert into cars (make, model, price) values ('Lexus', 'GS', '97306.91');
insert into cars (make, model, price) values ('Cadillac', 'Allante', '22402.71');
insert into cars (make, model, price) values ('Audi', 'riolet', '37911.17');
insert into cars (make, model, price) values ('Infiniti', 'QX', '24633.01');
insert into cars (make, model, price) values ('Ford', 'Probe', '63587.18');
insert into cars (make, model, price) values ('Chevrolet', 'Corvair 500', '82257.69');
insert into cars (make, model, price) values ('Mitsubishi', 'Truck', '63760.16');
insert into cars (make, model, price) values ('Chevrolet', 'Astro', '11695.78');
insert into cars (make, model, price) values ('Jeep', 'Wrangler', '21045.99');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice Classic', '57317.43');
insert into cars (make, model, price) values ('Smart', 'Fortwo', '79121.09');
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', '31534.07');
insert into cars (make, model, price) values ('Jeep', 'Patriot', '21223.23');
insert into cars (make, model, price) values ('Volvo', 'C70', '34009.18');
insert into cars (make, model, price) values ('Oldsmobile', 'Bravada', '32155.36');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '86522.23');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '49321.88');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '76374.70');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '30412.89');
insert into cars (make, model, price) values ('Dodge', 'Charger', '18662.39');
insert into cars (make, model, price) values ('BMW', '3 Series', '57134.34');
insert into cars (make, model, price) values ('Lexus', 'GX', '71517.98');
insert into cars (make, model, price) values ('Bentley', 'Continental', '99765.92');
insert into cars (make, model, price) values ('GMC', 'Sierra 3500', '24787.42');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '95937.50');
insert into cars (make, model, price) values ('Volvo', 'S60', '62719.94');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '32229.70');
insert into cars (make, model, price) values ('Mazda', 'Protege', '92721.20');
insert into cars (make, model, price) values ('Nissan', 'Pathfinder', '50611.34');
insert into cars (make, model, price) values ('Nissan', 'Frontier', '78311.33');
insert into cars (make, model, price) values ('BMW', 'Z3', '81530.54');
insert into cars (make, model, price) values ('Acura', 'TL', '26666.54');
insert into cars (make, model, price) values ('GMC', '1500 Club Coupe', '88207.75');
insert into cars (make, model, price) values ('Ford', 'Mustang', '75189.84');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '83988.06');
insert into cars (make, model, price) values ('Lexus', 'RX', '70782.33');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '33632.30');
insert into cars (make, model, price) values ('Kia', 'Optima', '24304.56');
insert into cars (make, model, price) values ('Chevrolet', 'Impala', '91864.63');
insert into cars (make, model, price) values ('Audi', 'A4', '98369.63');
insert into cars (make, model, price) values ('Kia', 'Carens', '70136.06');
insert into cars (make, model, price) values ('Mazda', 'MPV', '70074.64');
insert into cars (make, model, price) values ('Austin', 'Mini Cooper', '93651.94');
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt', '31674.09');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '47376.83');
insert into cars (make, model, price) values ('Plymouth', 'Voyager', '17628.05');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '13633.03');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '31587.71');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '95266.30');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice', '85584.86');
insert into cars (make, model, price) values ('Toyota', '4Runner', '58520.60');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '66942.07');
insert into cars (make, model, price) values ('Dodge', 'Intrepid', '46503.29');
insert into cars (make, model, price) values ('Saab', '9-3', '16402.93');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '40391.45');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500', '52348.15');
insert into cars (make, model, price) values ('Mazda', 'Tribute', '64606.16');
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', '63010.40');
insert into cars (make, model, price) values ('Acura', 'MDX', '62869.61');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '99989.63');
insert into cars (make, model, price) values ('Bentley', 'Continental', '75070.07');
insert into cars (make, model, price) values ('Volkswagen', 'CC', '54897.01');
insert into cars (make, model, price) values ('Mercedes-Benz', 'G-Class', '88546.08');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '98617.29');
insert into cars (make, model, price) values ('Ford', 'E150', '37523.43');
insert into cars (make, model, price) values ('Toyota', 'Sequoia', '89230.10');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '63417.16');
insert into cars (make, model, price) values ('Maybach', '57', '95012.34');
insert into cars (make, model, price) values ('Holden', 'VS Commodore', '88044.46');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '18234.39');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '72730.92');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '50874.81');
insert into cars (make, model, price) values ('Foose', 'Hemisfear', '30107.74');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '82615.80');
insert into cars (make, model, price) values ('Ford', 'E150', '12665.13');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg 2', '71082.84');
insert into cars (make, model, price) values ('Nissan', 'Altima', '33991.89');
insert into cars (make, model, price) values ('GMC', 'Savana 1500', '30915.78');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '67455.29');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '86578.90');
insert into cars (make, model, price) values ('Volkswagen', 'Fox', '97343.82');
insert into cars (make, model, price) values ('Buick', 'LaCrosse', '37442.39');
insert into cars (make, model, price) values ('Jaguar', 'XJ Series', '56347.13');
insert into cars (make, model, price) values ('Plymouth', 'Breeze', '81708.10');
insert into cars (make, model, price) values ('Ford', 'E-Series', '39125.69');
insert into cars (make, model, price) values ('Mazda', 'B-Series', '89802.15');
insert into cars (make, model, price) values ('Honda', 'Civic', '64368.12');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '35550.64');
insert into cars (make, model, price) values ('Kia', 'Sedona', '19171.93');
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', '31441.53');
insert into cars (make, model, price) values ('Acura', 'RSX', '87117.07');
insert into cars (make, model, price) values ('Volkswagen', 'Scirocco', '16478.28');
insert into cars (make, model, price) values ('Ford', 'Ranger', '13570.19');
insert into cars (make, model, price) values ('Ford', 'Taurus', '74018.25');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '26816.30');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '33815.17');
insert into cars (make, model, price) values ('Dodge', 'Neon', '54419.29');
insert into cars (make, model, price) values ('Ford', 'Windstar', '74381.16');
insert into cars (make, model, price) values ('Geo', 'Tracker', '83872.99');
insert into cars (make, model, price) values ('Ford', 'Mustang', '46372.25');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '62099.13');
insert into cars (make, model, price) values ('Infiniti', 'Q', '78437.57');
insert into cars (make, model, price) values ('Ford', 'Bronco', '31595.56');
insert into cars (make, model, price) values ('Hyundai', 'XG350', '75322.43');
insert into cars (make, model, price) values ('Pontiac', 'GTO', '94794.66');
insert into cars (make, model, price) values ('Mazda', 'CX-9', '65465.69');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 2500', '75477.48');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '52536.56');
insert into cars (make, model, price) values ('Volkswagen', 'Type 2', '68735.90');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '36228.72');
insert into cars (make, model, price) values ('Nissan', '370Z', '67676.87');
insert into cars (make, model, price) values ('Mazda', 'Millenia', '38602.53');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '18169.46');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '90881.45');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '39981.96');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '22337.82');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '97399.10');
insert into cars (make, model, price) values ('Ram', 'C/V', '81289.35');
insert into cars (make, model, price) values ('Kia', 'Sorento', '60939.66');
insert into cars (make, model, price) values ('Kia', 'Rondo', '30323.14');
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', '74104.98');
insert into cars (make, model, price) values ('Buick', 'Skylark', '11932.66');
insert into cars (make, model, price) values ('Volvo', 'C70', '66553.86');
insert into cars (make, model, price) values ('Toyota', 'Yaris', '25276.59');
insert into cars (make, model, price) values ('Lotus', 'Evora', '60725.57');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 3500', '59418.86');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '66750.88');
insert into cars (make, model, price) values ('Lexus', 'LS', '70261.91');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '30571.74');
insert into cars (make, model, price) values ('Mazda', 'Mazda6', '62777.60');
insert into cars (make, model, price) values ('Maserati', 'Spyder', '41422.89');
insert into cars (make, model, price) values ('Ford', 'Taurus', '84017.53');
insert into cars (make, model, price) values ('Audi', 'A4', '36798.11');
insert into cars (make, model, price) values ('Audi', '5000S', '23881.73');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '79099.34');
insert into cars (make, model, price) values ('BMW', '550', '55529.81');
insert into cars (make, model, price) values ('Dodge', 'Journey', '83908.04');
insert into cars (make, model, price) values ('Citroën', 'CX', '68621.59');
insert into cars (make, model, price) values ('Acura', 'Integra', '32141.98');
insert into cars (make, model, price) values ('Scion', 'xB', '39991.94');
insert into cars (make, model, price) values ('Dodge', 'Stratus', '28932.27');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '47561.93');
insert into cars (make, model, price) values ('Lexus', 'ES', '12263.17');
insert into cars (make, model, price) values ('Lexus', 'IS', '47561.01');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '68915.95');
insert into cars (make, model, price) values ('Buick', 'Century', '98623.55');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '17603.80');
insert into cars (make, model, price) values ('Cadillac', 'Seville', '58552.73');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '62182.87');
insert into cars (make, model, price) values ('Mitsubishi', 'Cordia', '25327.50');
insert into cars (make, model, price) values ('Chevrolet', 'Sportvan G30', '63573.00');
insert into cars (make, model, price) values ('Isuzu', 'Stylus', '53329.46');
insert into cars (make, model, price) values ('Lincoln', 'MKS', '77312.13');
insert into cars (make, model, price) values ('Audi', 'Allroad', '52746.35');
insert into cars (make, model, price) values ('Lexus', 'SC', '43757.74');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '59717.44');
insert into cars (make, model, price) values ('Dodge', 'Stealth', '37256.19');
insert into cars (make, model, price) values ('Volkswagen', 'Type 2', '79415.11');
insert into cars (make, model, price) values ('GMC', 'Rally Wagon 3500', '11295.15');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '73216.60');
insert into cars (make, model, price) values ('Suzuki', 'Sidekick', '15612.86');
insert into cars (make, model, price) values ('Volvo', 'XC90', '25214.31');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '69819.40');
insert into cars (make, model, price) values ('Pontiac', 'LeMans', '29992.34');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 1500', '93876.43');
insert into cars (make, model, price) values ('Dodge', 'D250', '94938.65');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '59505.54');
insert into cars (make, model, price) values ('Mazda', 'Mazda3', '82848.38');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '62240.49');
insert into cars (make, model, price) values ('Volkswagen', 'Passat', '85586.38');
insert into cars (make, model, price) values ('Hyundai', 'Genesis', '33223.42');
insert into cars (make, model, price) values ('Mitsubishi', 'Sigma', '90684.40');
insert into cars (make, model, price) values ('Chevrolet', 'S10', '23301.01');
insert into cars (make, model, price) values ('Scion', 'tC', '99927.13');
insert into cars (make, model, price) values ('Porsche', '968', '11400.93');
insert into cars (make, model, price) values ('GMC', '2500 Club Coupe', '62173.66');
insert into cars (make, model, price) values ('Plymouth', 'Voyager', '33603.59');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '37947.28');
insert into cars (make, model, price) values ('BMW', 'Z3', '23261.80');
insert into cars (make, model, price) values ('Nissan', 'Armada', '33685.90');
insert into cars (make, model, price) values ('BMW', 'M3', '87738.65');
insert into cars (make, model, price) values ('Buick', 'Skylark', '36843.30');
insert into cars (make, model, price) values ('Jaguar', 'XK', '83864.92');
insert into cars (make, model, price) values ('Ford', 'Econoline E350', '53535.61');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '42278.61');
insert into cars (make, model, price) values ('Lotus', 'Elise', '55299.11');
insert into cars (make, model, price) values ('Toyota', 'Highlander', '65798.32');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '97961.66');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '52377.91');
insert into cars (make, model, price) values ('Buick', 'Regal', '58354.23');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '46965.71');
insert into cars (make, model, price) values ('Pontiac', 'Firefly', '55834.26');
insert into cars (make, model, price) values ('Buick', 'Skylark', '64034.95');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '81189.72');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '41539.15');
insert into cars (make, model, price) values ('Eagle', 'Talon', '38286.73');
insert into cars (make, model, price) values ('Mitsubishi', 'Expo', '81856.48');
insert into cars (make, model, price) values ('Lincoln', 'Navigator', '24040.00');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '15269.07');
insert into cars (make, model, price) values ('Chrysler', 'PT Cruiser', '14539.73');
insert into cars (make, model, price) values ('Honda', 'CR-V', '85369.26');
insert into cars (make, model, price) values ('Infiniti', 'QX', '26989.95');
insert into cars (make, model, price) values ('Dodge', 'Ram', '72296.17');
insert into cars (make, model, price) values ('Chevrolet', 'Aveo', '56515.61');
insert into cars (make, model, price) values ('Ford', 'F150', '17603.28');
insert into cars (make, model, price) values ('Ford', 'E-Series', '31008.03');
insert into cars (make, model, price) values ('Lexus', 'IS', '66997.17');
insert into cars (make, model, price) values ('GMC', 'Vandura 1500', '76614.30');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '96715.91');
insert into cars (make, model, price) values ('BMW', 'Z4', '31011.38');
insert into cars (make, model, price) values ('Dodge', 'Viper', '54884.00');
insert into cars (make, model, price) values ('Porsche', 'Cayenne', '37018.91');
insert into cars (make, model, price) values ('Lexus', 'GS', '88776.27');
insert into cars (make, model, price) values ('Mazda', 'MPV', '82784.57');
insert into cars (make, model, price) values ('GMC', '2500', '81885.59');
insert into cars (make, model, price) values ('BMW', '5 Series', '59172.91');
insert into cars (make, model, price) values ('Audi', '5000S', '64594.87');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '69094.45');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '54678.17');
insert into cars (make, model, price) values ('Mitsubishi', 'Diamante', '14464.34');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '67956.01');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '66551.53');
insert into cars (make, model, price) values ('Suzuki', 'Forenza', '71952.36');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 1500', '99040.63');
insert into cars (make, model, price) values ('Mazda', '626', '55702.10');
insert into cars (make, model, price) values ('Infiniti', 'FX', '66933.59');
insert into cars (make, model, price) values ('Aston Martin', 'Rapide', '45614.44');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '58473.81');
insert into cars (make, model, price) values ('Toyota', 'Camry Hybrid', '58894.05');
insert into cars (make, model, price) values ('Honda', 'Passport', '44179.41');
insert into cars (make, model, price) values ('Nissan', 'Versa', '45842.20');
insert into cars (make, model, price) values ('Dodge', 'Viper', '66445.56');
insert into cars (make, model, price) values ('Acura', 'NSX', '85245.64');
insert into cars (make, model, price) values ('Dodge', 'Ram Wagon B350', '92487.22');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '63099.15');
insert into cars (make, model, price) values ('Saab', '9-3', '46431.56');
insert into cars (make, model, price) values ('Suzuki', 'Sidekick', '23970.92');
insert into cars (make, model, price) values ('Lexus', 'RX', '54957.43');
insert into cars (make, model, price) values ('Ford', 'LTD Crown Victoria', '18902.78');
insert into cars (make, model, price) values ('Chrysler', '200', '59101.88');
insert into cars (make, model, price) values ('Mercury', 'Topaz', '47116.15');
insert into cars (make, model, price) values ('Chevrolet', 'S10', '16472.29');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '83183.06');
insert into cars (make, model, price) values ('Cadillac', 'DeVille', '16352.40');
insert into cars (make, model, price) values ('Volkswagen', 'Cabriolet', '19635.46');
insert into cars (make, model, price) values ('Lincoln', 'Mark VIII', '86116.35');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '95542.77');
insert into cars (make, model, price) values ('Hyundai', 'HED-5', '61207.88');
insert into cars (make, model, price) values ('Mazda', '929', '54853.06');
insert into cars (make, model, price) values ('Suzuki', 'Reno', '53655.24');
insert into cars (make, model, price) values ('Ford', 'F350', '89136.66');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '30143.00');
insert into cars (make, model, price) values ('Jaguar', 'XJ', '60265.12');
insert into cars (make, model, price) values ('Ferrari', '612 Scaglietti', '87093.82');
insert into cars (make, model, price) values ('Chevrolet', 'Avalanche', '98828.57');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '84783.14');
insert into cars (make, model, price) values ('Kia', 'Sorento', '64768.62');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '18589.54');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '16212.43');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '27403.70');
insert into cars (make, model, price) values ('Buick', 'Skyhawk', '48479.55');
insert into cars (make, model, price) values ('Pontiac', 'Sunfire', '36517.49');
insert into cars (make, model, price) values ('Nissan', 'Murano', '80056.69');
insert into cars (make, model, price) values ('Buick', 'Century', '33624.58');
insert into cars (make, model, price) values ('Toyota', 'Camry', '46655.93');
insert into cars (make, model, price) values ('Mercedes-Benz', '600SEL', '84277.56');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '57432.92');
insert into cars (make, model, price) values ('Subaru', 'XT', '99785.98');
insert into cars (make, model, price) values ('BMW', '525', '23403.79');
insert into cars (make, model, price) values ('Porsche', '944', '10068.59');
insert into cars (make, model, price) values ('GMC', 'Sierra 3500', '37008.91');
insert into cars (make, model, price) values ('Cadillac', 'CTS-V', '10109.80');
insert into cars (make, model, price) values ('Acura', 'ZDX', '84327.99');
insert into cars (make, model, price) values ('Mitsubishi', 'GTO', '69463.13');
insert into cars (make, model, price) values ('Chrysler', 'PT Cruiser', '13214.74');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '86581.54');
insert into cars (make, model, price) values ('Buick', 'Somerset', '52189.93');
insert into cars (make, model, price) values ('Chrysler', 'Cirrus', '18073.54');
insert into cars (make, model, price) values ('Chevrolet', 'Colorado', '98528.90');
insert into cars (make, model, price) values ('Cadillac', 'SRX', '35634.65');
insert into cars (make, model, price) values ('Mitsubishi', '3000GT', '80234.55');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 3500HD', '81741.56');
insert into cars (make, model, price) values ('Honda', 'Pilot', '32807.47');
insert into cars (make, model, price) values ('Jeep', 'Patriot', '55857.95');
insert into cars (make, model, price) values ('BMW', '530', '27262.51');
insert into cars (make, model, price) values ('Acura', 'SLX', '75236.41');
insert into cars (make, model, price) values ('Mazda', '929', '23080.14');
insert into cars (make, model, price) values ('Lexus', 'LX', '96421.44');
insert into cars (make, model, price) values ('Ford', 'Flex', '34585.75');
insert into cars (make, model, price) values ('Aston Martin', 'V8 Vantage', '82047.48');
insert into cars (make, model, price) values ('Jeep', 'Compass', '99070.14');
insert into cars (make, model, price) values ('Ford', 'Mustang', '35456.62');
insert into cars (make, model, price) values ('Honda', 'CR-V', '86788.53');
insert into cars (make, model, price) values ('Mitsubishi', 'Expo', '77669.36');
insert into cars (make, model, price) values ('Honda', 'Odyssey', '61783.60');
insert into cars (make, model, price) values ('Audi', 'Q5', '25979.73');
insert into cars (make, model, price) values ('Ford', 'Mustang', '36520.28');
insert into cars (make, model, price) values ('Chevrolet', 'Impala', '62244.39');
insert into cars (make, model, price) values ('BMW', 'Z4', '26446.72');
insert into cars (make, model, price) values ('Lexus', 'GX', '77818.61');
insert into cars (make, model, price) values ('Infiniti', 'Q', '32193.88');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '46907.81');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban', '91560.65');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '69042.21');
insert into cars (make, model, price) values ('MINI', 'Cooper', '61915.58');
insert into cars (make, model, price) values ('Pontiac', 'LeMans', '87950.24');
insert into cars (make, model, price) values ('Cadillac', 'DeVille', '65182.45');
insert into cars (make, model, price) values ('Cadillac', 'Brougham', '59112.65');
insert into cars (make, model, price) values ('Volvo', 'V70', '90464.51');
insert into cars (make, model, price) values ('Chevrolet', 'G-Series G20', '89593.95');
insert into cars (make, model, price) values ('Lotus', 'Elise', '34307.99');
insert into cars (make, model, price) values ('BMW', 'X3', '27335.30');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '59082.91');
insert into cars (make, model, price) values ('Saab', '9-3', '89750.27');
insert into cars (make, model, price) values ('Hummer', 'H2 SUV', '60383.73');
insert into cars (make, model, price) values ('Audi', 'A4', '91643.38');
insert into cars (make, model, price) values ('Audi', 'A3', '96917.83');
insert into cars (make, model, price) values ('Dodge', 'Durango', '12553.41');
insert into cars (make, model, price) values ('Hummer', 'H3', '53145.47');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '65999.55');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', '97833.88');
insert into cars (make, model, price) values ('Ford', 'Windstar', '94349.79');
insert into cars (make, model, price) values ('Ford', 'Focus', '97572.43');
insert into cars (make, model, price) values ('Bentley', 'Continental GTC', '46432.45');
insert into cars (make, model, price) values ('Mazda', 'MX-3', '74935.57');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '97686.35');
insert into cars (make, model, price) values ('Ford', 'Econoline E250', '89331.54');
insert into cars (make, model, price) values ('Ford', 'Taurus', '96723.20');
insert into cars (make, model, price) values ('Jeep', 'Wrangler', '18605.73');
insert into cars (make, model, price) values ('Subaru', 'Forester', '42626.56');
insert into cars (make, model, price) values ('BMW', 'M3', '56934.69');
insert into cars (make, model, price) values ('Honda', 'Civic', '66381.09');
insert into cars (make, model, price) values ('Mitsubishi', 'Endeavor', '43847.18');
insert into cars (make, model, price) values ('GMC', 'Sierra Denali', '81539.29');
insert into cars (make, model, price) values ('Ford', 'Expedition EL', '53477.24');
insert into cars (make, model, price) values ('Mercury', 'Marauder', '88448.04');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '64261.87');
insert into cars (make, model, price) values ('Hyundai', 'HED-5', '45560.06');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '39361.92');
insert into cars (make, model, price) values ('Dodge', 'Viper', '91417.30');
insert into cars (make, model, price) values ('Ford', 'Fusion', '54846.67');
insert into cars (make, model, price) values ('Mazda', 'B-Series Plus', '74213.88');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '29063.92');
insert into cars (make, model, price) values ('Mazda', '929', '60389.48');
insert into cars (make, model, price) values ('BMW', 'X5', '12549.50');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '36475.16');
insert into cars (make, model, price) values ('Infiniti', 'G37', '99155.58');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '17571.44');
insert into cars (make, model, price) values ('Volkswagen', 'Eurovan', '37329.49');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '11615.93');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '33759.83');
insert into cars (make, model, price) values ('Audi', 'S4', '25740.47');
insert into cars (make, model, price) values ('Subaru', 'Alcyone SVX', '30310.19');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '43477.64');
insert into cars (make, model, price) values ('Ford', 'Fusion', '12185.28');
insert into cars (make, model, price) values ('Audi', 'RS 4', '15391.48');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '85154.07');
insert into cars (make, model, price) values ('Mitsubishi', 'Truck', '81679.10');
